CREATE DATABASE DESAFIO_FINAL;
GO
USE DESAFIO_FINAL;
GO
CREATE TABLE TB_CLIENTS(
	ID INT NOT NULL
	,NOME VARCHAR(250) NOT NULL
	,EMAIL VARCHAR(250) NOT NULL
	,DATA_CADASTRO DATETIME NOT NULL
	,TELEFONE VARCHAR(16)
	,PRIMARY KEY (ID)
);
GO
CREATE TABLE TB_TRANSACTION(
	ID INT NOT NULL
	,CLIENT_ID INT NOT NULL
	,VALOR FLOAT NOT NULL
	,DATA DATETIME
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES TB_CLIENTS(ID)
);
